### ISSUE TITLE
Not seeing/reading   other trainers 

### ISSUE THREAD

**Issue by Laz55** [SheffeyG/CheatDeck#10]
Hi

There are a few bugs in this plug-in ;for example  Dave  The  Driver  Fling  trainer will not pop up  alone with thr following  lists of game trainers.  

Starfield,  Generation Zero, Baldours  Gate  3 , Dave The Diver,  Armoured Core 6, Elden Ring  , Atla Fallen & Grlubded all those latest  trainers  by Fling will not pop-up  meaning Trigger. 

Also, Mrantifun trainers  do not appear  when trying too find the files;such as, Far Cry 2 , Red Faction  Guerilla,  Red Faction  Armageddon  Mrantifun trainers don't seem too shown by the program  meaning cheatdeck  can't  find or see the files  even when you toggle hidden  files.

**Comment by SheffeyG** [comment]
@Laz55 Generally, press the `steam` key, you can switch between the game and cheat winows, if some of your cheat didn't pop up or show, that might be the cheat's problem, maybe wrong cheat version or something. If all cheat never show, just check the dev mode and cef debug option, make sure they all enabled.
about the trainers file, is they exe file? the default file filter is only exe format, if there is another format trainer, please tell me that, I will add it.

**Comment by Laz55** [comment]
Hi

the steps you mentioned I literally just did. This has nothing to do with
what you  said meaning cef debug option is enabled and thats not the issue
at hand . You can test it out for yourself. Dave The Diver Fling Trainer Or
Baldur's gate 3 do not work meaning the fork function will not respond.
The 3 Mranti fun trainers i listed are exe files yet the program can not
find them or see them I stated that. You can even test those trainers i
listed.

https://mrantifun.net/threads/red-faction-armageddon-trainer.11654/

https://mrantifun.net/threads/red-faction-guerrilla-steam-edition-trainer.22499/

https://mrantifun.net/threads/far-cry-2-trainer.3344/


you can test this by using any game and when you try too find the
downloaded trainers the cheatdeck cannot locate them.

**Comment by SheffeyG** [comment]
@Laz55 it turns out these trainer end with `EXE` not `exe`, I didnt expect that. anyway, I will add it to file filter in next version

**Comment by Sweetcheezus** [comment]
Glad I'm not the only one having this issue. Appreciate you looking into it and being willing to improve it. Definitely looking forward to the next version and thanks for the time you put into this!

**Comment by SheffeyG** [comment]
@Laz55 @Sweetcheezus The github release is always sonner than decky store, you can install them with the url from pre release note. glad to hear you like this plugin, you can star this project to keep the least version from here and support it.

**Comment by Sweetcheezus** [comment]
I downloaded the .zip file from the URL but what do I from there to install it? I'm newer to Steam Deck as I just got it a couple weeks ago.

**Comment by SheffeyG** [comment]
Enable the developer mode of decky store, paste the url to dev setting `install from url`

**Comment by Sweetcheezus** [comment]
Thanks a lot! I'll test this version out and see if it works better with Fling trainers.

**Comment by Laz55** [comment]
I tried that and it won't  let me copy paste in game  mode.

**Comment by SheffeyG** [comment]
Go desktop mode dowload the zip file. and install from zip file. If not you can wait the store version
