### ISSUE TITLE
Trainer not accepting inputs + Steam UI broken after using CheatDeck

### ISSUE THREAD

**Issue by subworx** [SheffeyG/CheatDeck#17]
I tried to play Bayonetta (Steam, v1.01) with [Fling's Trainer for v1.01](https://archive.flingtrainer.com/files/Bayonetta%20v1.0-v1.01%20Plus%2011%20Trainer.rar) using CheatDeck 0.3.1 on stable SteamOS/Steam Client.
It works perfectly fine in Windows, the Num keys toggle the options as usual, this trainer does not support mouse inputs.

On the Steam Deck inside CheatDeck, I set the path to the trainer. The game loads, the trainer as well. I can switch between the windows without problem, but cannot trigger any option due to missing button assignments and no mouse support.

I tried to change controller settings to set the left trackpad to Touch Menu, assigning the keys Num1 - Num9.
Here comes the UI Problem: This did not work, I could not change the trackpad mode, nothing happened when opening any dropdown or overlay. I managed to exit the game (it would not react to Steam -> Game -> Exit), but could not restart the Steam Deck either, as the power menu stopped showing up, no matter if I held the power button or used Steam -> Power.
Things like changing controls from the game's main page and the settings menu for the game stopped working as well.
This happened reproducably, and I had to force reboot the device (or remote in with SSH and issue a restart/reboot once at home).

After the reboot, I set up the Touch Menu with Num keys and started the game again.
Still, the trainer does not react to any of the keys, neither with confirmation sound nor with any effect on the game.

Please let me know if you need any more info, or how I can provide a log, or whatever.
Thanks.

**Comment by SheffeyG** [comment]
@subworx Generally use the touch screen instead of the touchpad to click the cheat panel, if not work you can try turn the game from fullscreen into windowed mode in the game inner settings.
As the UI problem, I don't think it's an issue with plugins, that is how steamdeck works, its input pattern sucks.

**Comment by boivinx7** [comment]
I have the same issue no input working, only tested with a fling trainer and Lost Judgment. Also the game says new games so seems its not tacking the cloud save for some reason. I get that with Proton i could make a new path because its a new app or something like that but cloud save should restore the save. So anyway in my current case its unusable but i like the idea of the add in.

**Comment by debojit7** [comment]
Can confirm, I am having the same issue with Bioshock Remastered Fling trainer. In my case, I set the L4 and R4 back buttons to numpad 1 and numpad 2. But during game no matter how many times I press them, there is no response.

**Comment by debojit7** [comment]
> Can confirm, I am having the same issue with Bioshock Remastered Fling trainer. In my case, I set the L4 and R4 back buttons to numpad 1 and numpad 2. But during game no matter how many times I press them, there is no response.

Never mind, I figured it out. Basically have to assign another button as the numlock button. By default the numlock is not on, so you have to press a button to activate the numlock and then press whatever button you have assigned for the cheat.

**Comment by boivinx7** [comment]
got it working by simply switching to the game then switching back to the trainer, was able to user [steam]+trackpad has a mouse cursor and was able to switch cheats ON. Realised that when i plugged a keyboard in and tried to the the shortcut to enable a cheat and the game reacted in the background but not the trainer.
