### ISSUE TITLE
setState do not work

### ISSUE THREAD

**Issue by sheffeyG** [sheffeyG/CheatDeck#2]
I met a problem when I tried to change the `showPath` s value from the initial value to the result of filepicker, but the `setShowPath` didn't work as I expect
<img width="571" alt="屏幕截图 2023-12-05 182436" src="https://github.com/sheffeyG/CheatDeck/assets/57262511/c4692287-0dcc-480b-bb29-cde3a3112459">
it turns out
<img width="433" alt="屏幕截图 2023-12-05 183255" src="https://github.com/sheffeyG/CheatDeck/assets/57262511/a10db0d6-b20c-492a-aff4-196fa3dbd078">
the showpath keeps the initial value which should be the result of filepicker
I know the setState would take a bit to refresh, but as a react noob, I am not sure where the problem is, bcz the code would be fine only if I replace the filepicker function to something else.
Any advice?

**Comment by sheffeyG** [comment]
Thanks to @nilsve, now I can keep going to this silly project

**Comment by doZennn** [comment]
Glad you got it working!
