### ISSUE TITLE
Unable to disable cheat once it’s enabled.

### ISSUE THREAD

**Issue by calvincorrieri** [SheffeyG/CheatDeck#27]
I pressed the enable cheat toggle, and selected an exe. Now if I try to disable the cheat, the toggle will move to the off position, but after exiting the page, it will become enabled again. This is very annoying behavior.

I’m hoping a fix will be released soon, but in the meantime, is there a file somewhere I can edit to disable it manually?

**Comment by SheffeyG** [comment]
You should **save settings** after disable cheat or other editing.
