### ISSUE TITLE
Not issue but feature request

### ISSUE THREAD

**Issue by darealcaffeine** [SheffeyG/CheatDeck#29]
Is it possible to have a feature to delay launch?

If not then can .bat files be selectable?

thanks!!!

**Comment by SheffeyG** [comment]
@darealcaffeine Hi, you can check this #5, and .bat files could be selectable, do you mean select it via filepicker in this plugin?

**Comment by darealcaffeine** [comment]
Yup via the plugin. Bat files doesn’t appear in the file picker. Thanks for the response btw :)

**Comment by SheffeyG** [comment]
@darealcaffeine You can test this [build](https://github.com/SheffeyG/CheatDeck/actions/runs/9933138369/artifacts/1700207930), and would you mind to show the bat script you use to delay launch trainer?
