### ISSUE TITLE
Where to put the trainer?

### ISSUE THREAD

**Issue by j3nesis87** [SheffeyG/CheatDeck#3]
How do you use this? Where do you put the trainer (Fling or otherwise)? How do you activate it?

**Comment by SheffeyG** [comment]
@j3nesis87 there are some steps:
1. Enable the developer mode at steam system settings.
2. Download the cheat or trainer you need in your steamdeck.
3. Navigate to the game details menu, and find the `cheat` item.
4. Enable the cheat setting and select the cheat exe file you just downloaded, then save settings.
5. Launch the game, and the cheat windows should be shown, if not, press the `steam` key, you can switch the game and cheat windows.
