### ISSUE TITLE
{bug} cheatdeck Desktop mode crash pop-up window

### ISSUE THREAD

**Issue by lzq960605** [SheffeyG/CheatDeck#31]
![Screenshot_20240822_174807](https://github.com/user-attachments/assets/d3745762-0db0-451d-aa2a-f69825d8fb8f)
![Screenshot_20240822_174828](https://github.com/user-attachments/assets/6579242a-c5fc-47d8-b3a8-5c1f799251bd)
![Screenshot_20240822_174843](https://github.com/user-attachments/assets/03f37481-d71e-4a1e-b41e-f11cd3d1014b)

[cef_log.previous.txt](https://github.com/user-attachments/files/16708832/cef_log.previous.txt)

[cef_log.txt](https://github.com/user-attachments/files/16708845/cef_log.txt)

**Comment by SheffeyG** [comment]
This error is not from cheatdeck or any plugins, and I noticed you are using decky 3.0 instead of the stable release, please report it to upstream [decky loader](https://github.com/SteamDeckHomebrew/decky-loader)

**Comment by eXhumer** [comment]
@SheffeyG See https://github.com/SteamGridDB/decky-steamgriddb/commit/dc9de954aff9c1783e8ed8ddfa4a76759304f4c6

Needs to be ported to fix issue.

**Comment by lzq960605** [comment]
> @SheffeyG See [](https://github.com/SteamGridDB/decky-steamgriddb/commit/dc9de954aff9c1783e8ed8ddfa4a76759304f4c6)
> 
> Needs to be ported to fix issue.

So do I have to wait for cheatdeck to update to a new version? I'm using the official version 3.0 of decky and it seems I still encounter this problem

**Comment by eXhumer** [comment]
https://github.com/SheffeyG/CheatDeck/actions/runs/10822590989
