### ISSUE TITLE
New release to fix decky-loader v3

### ISSUE THREAD

**Issue by eXhumer** [SheffeyG/CheatDeck#33]
With the release of decky-loader v3, there was an issue with CheatDeck crashing Steam in Desktop Mode. Issue is fixed (a01a47d5aa5f62a88ccc23a4e4552f6a34fcc515), but a new release of the plugin to the decky store needs to be pushed so that all users are able to get the update. Consider a new release when you have the time. Thanks.

**Comment by eXhumer** [comment]
Just an FYI, CheatDeck has been currently pulled from Decky Store as it breaks Steam in Desktop Mode.

**Comment by SheffeyG** [comment]
v0.3.2 is about to test now.

**Comment by NeoTheOne** [comment]
Any way to install it manually for now?

**Comment by eXhumer** [comment]
Download and install the artifact from the following.

https://github.com/SheffeyG/CheatDeck/actions/runs/10864091232

**Comment by NeoTheOne** [comment]
> Download and install the artifact from the following.
> 
> https://github.com/SheffeyG/CheatDeck/actions/runs/10864091232

Thank you, works.

**Comment by furuowei** [comment]
该如何操作

**Comment by dannyl1017** [comment]
> > Download and install the artifact from the following.
> > https://github.com/SheffeyG/CheatDeck/actions/runs/10864091232
> 
> Thank you, works.

Do you have steps on how to install the artifact?

**Comment by SheffeyG** [comment]
@dannyl1017 Enable developer mode in the Decky Loader settings, then you can install the plugin with the zip file or from the url.

**Comment by skylaic** [comment]
> @dannyl1017 Enable developer mode in the Decky Loader settings, then you can install the plugin with the zip file or from the url.

When I installed it to about 99%, it stopped moving。

**Comment by dannyl1017** [comment]
> @dannyl1017 Enable developer mode in the Decky Loader settings, then you can install the plugin with the zip file or from the url.

THANK YOU SO MUCH IT WORKS NOW!!!!!!!!!

**Comment by Veidddt** [comment]
> @dannyl1017 Enable developer mode in the Decky Loader settings, then you can install the plugin with the zip file or from the url.

It stuck at "parsing zip file" and didnt move again

**Comment by eXhumer** [comment]
Just download it from the testing store since so many seem to unable to install a ZIP for whatever reason.

In Decky settings, change the Store channel to "Testing" and download CheatDeck from Decky Store.

**Comment by GrizzlyFoxCat** [comment]
Installing from the Testing store does nothing. It completes the installation but nothing shows up in decky or in the game details.

**Comment by GrizzlyFoxCat** [comment]
> @dannyl1017 Enable developer mode in the Decky Loader settings, then you can install the plugin with the zip file or from the url.

I can't seem to download the zip file, there's no link to any files in the linked page, 😞 

Do I need to be logged in to GitHub?

**Comment by eXhumer** [comment]
https://github.com/user-attachments/assets/13e8db59-2c51-43fe-ba70-02d6f165cb95

For those looking how to install CheatDeck from testing store

**Comment by Mte90** [comment]
any updates for this official release?

**Comment by eXhumer** [comment]
> any updates for this official release?

https://wiki.deckbrew.xyz/user-guide/testing

SteamDeckHomebrew/decky-plugin-database#695

**Comment by eXhumer** [comment]
A new release has been merged into the decky-plugin-database and CheatDeck now can again be downloaded from the Decky Store directly. This issue will now be closed.
