### ISSUE TITLE
How to use custom cheats 

### ISSUE THREAD

**Issue by Ryderjey** [SheffeyG/CheatDeck#37]
Hi guys, hope I can get some help from you, greetings from Ecuador, I have been searching for a way to use the custom cheat maker in your cheat deck, but I can't find a way, could you help me with please ? Dunno what's the type of cheat code I need to input it, I tried, GameShark codes and other kinds and doesn't work. 
![17278297663518685631703018585774](https://github.com/user-attachments/assets/8b5a6036-f4e8-43f9-8b18-265046cc4750)

**Comment by eXhumer** [comment]
The "Custom" field is present to add custom environment variables to the launching application, it is not used add custom cheats. CheatDeck does not and will not support any custom cheats. All it does is launch an external application in the same compatibility layer as the launching game.

You can use it to launch a trainer, memory editor (like CheatEngine) or any other kinds of supported executables.
