### ISSUE TITLE
Feature request: Mangohud fps limit launch command

### ISSUE THREAD

**Issue by TheFloGus** [SheffeyG/CheatDeck#38]
Hi! 

I really like your plugin and I noticed in advanced settings you can basically add any launch command you wanted. It would've been nice to add the option of Mangohud fps limit. 
The command looks something like this: 
"MANGOHUD_CONFIG=fps_limit=30,fps_limit_method=early,no_display mangohud %command%"
 The problem with built in steam fps limiter is that it add a lot of lag, especially at lower framerates. And game fps limiters are usually pretty wonky and inconsistent. 

I looked through your code and found there is a slider component in decky ui api and I thought you could use that. I tried doing it myself, but unfortunately it didn't work

I know this feature may not be very popular, but I'm sure some people like me would appreciate it! 

Thanks!

**Comment by TheFloGus** [comment]
>But you can still do it by making a custom option, it's made for someone like you!

Thanks! It does work, but I found a scrip which allows to shorten the whole line to "fps -f 30 %command%" and unfortunately looks like custom command only allows to be written with "=" sign. It would be nice to allow the command just with value. Basically just write it and it adds %command% at the end

**Comment by SheffeyG** [comment]
`fps -f 30 %command%` this one looks like a steam built-in command? not sure.
I didn't realize there're commands without a `=` in it exists, will check what to do later.

**Comment by TheFloGus** [comment]
No. It's also Mangohud, but someone wrote a script that you add to PATH and it basically launch it with `fps` line and it takes symbols after that and puts them in Mangohud config. At least as I understand it. The script was called "mangolimiter", but you can call the file whatever and it works

https://github.com/TiZ-HugLife/configs-scripts/blob/main/scripts/mangolimiter

Here is the file and instructions on how it works. So yeah I'm probably the only one doing that 😀

**Comment by SheffeyG** [comment]
I see, so the proton launch options still have a `=` inside, that's great!
