### ISSUE TITLE
Auto-refresh trainer window not working

### ISSUE THREAD

**Issue by areymoreno** [SheffeyG/CheatDeck#4]
When you select one option, and you want another you have to switch between windows, wouldn't it be possible to refresh the trainer window so you don't have to switch between windows constantly?

**Comment by SheffeyG** [comment]
I guess you are saying to switch the windows automatically? the cheats or trainers may provide multiple options( I didn't make them), so I don't think we should make it switch automatically, if I understand it wrong, can you explain it more specifically?

**Comment by areymoreno** [comment]
Of course, imagine you have "Game" and "Trainer".

When I turn on trick 1 of the trainer, I have to switch between the trainer window and the game to be able to activate the next trick and so on, I don't know if it would be possible to have an automatic refresh so I don't have to do this process every time.

I don't know if it would be possible to have an automatic refresh so that I don't have to go through the whole process every time, or if it could be a chaos of programming.

Best regards.

**Comment by SheffeyG** [comment]
That is depends on what cheat or trainer we use, I guess. I just test hollow knight with the trainer from fling, I can choose multiple tricks once, without switch back to game window to activate it. are you using wemod or something else?
